### ISSUE TITLE
Please provide GPL licensing

### ISSUE THREAD

**Issue by jketterl** [alexander-sholohov/msk144decoder#1]
I have been made aware of your decoder for integration in [OpenWebRX](https://github.com/jketterl/openwebrx/issues/257).

I'm facing a problem with the licensing of your project: Your code is licensed under the MIT license, but at the same time integrates code from the WSJT-X project by use of git submodules, which is licensed under GPL. My understanding is that the GPL requires that whatever results from this combination must be licensed under GPL.

While this may be fine for an audience who would be compiling this project from source, I would also like to distribute binaries for those who prefer a simpler installation method. The current constellation does not allow me to do this: I am not the author of any of the involved code, so I cannot change the license at will, and as such am unable to fulfill the GPL's conditions.

Would you consider adding the GPLv3 as an alternate licensing option?

**Comment by alexander-sholohov** [comment]
Thank you for noticing. I've added GPLv3 license.

**Comment by jketterl** [comment]
Thank you very much :)
